captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
cors:
  mode: whitelist
  whitelist:
  - allow-origin: example1.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
  - allow-origin: example2.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
db-list:
- disable: false
  type: ""
  alias-name: ""
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
excel:
  dir: ./resource/excel/
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: qmPlus
  signing-key: d08ea153-3e5a-4572-b467-3441abdd5c81
local:
  path: uploads/file
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: lemon
  username: root
  password: "12345678"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
timer:
  start: true
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
  - tableName: jwt_blacklists
    compareField: created_at
    interval: 168h
zap:
  level: info
  format: console
  prefix: '[github.com/yunfei07/lemon/server]'
  director: log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
